version: '3.6'
services:
  auth:
    build:
      context: ./tomcat
    image: tokyomap.oauth.auth:dev
    container_name: tokyomap-oauth-auth
    privileged: true
    ports:
      - "80:8080"
    volumes:
      - ./tomcat/logs:/usr/share/tomcat/logs
      - ./tomcat/webapps:/usr/share/tomcat/webapps
  postgres:
    image: postgres:latest
    container_name: tokyomap-oauth-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./postgres/hgsql/data:/var/lib/hgsql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./postgres/csv:/var/tmp
    ports:
      - "5432:5432"
